#ifndef __SETTINGS_H__
#define __SETTINGS_H__

#define CONFIG_IDF_TARGET_ESP32 1
#define ESP_CONNECT_LOGGING_LEVEL ESP_LOG_INFO

#define UART_NO UART_NUM_1
#define UART_BAUDRATE (115200)
//#define UART_BAUDRATE (230400)
#define UART_RX_BUFFER_SIZE (4096)
#define UART_TX_BUFFER_SIZE (4096)

#define UART_TIMEOUT_MS 50000
#define UART_TX  GPIO_NUM_17
#define UART_RX  GPIO_NUM_16
#define UART_RTS GPIO_NUM_18
#define UART_CTS GPIO_NUM_19

#define ID_LOG_MESSAGE (32700)

#endif
