#ifndef __SETTINGS_H__
#define __SETTINGS_H__

#define configSUPPORT_DYNAMIC_ALLOCATION 1
#define configUSE_RECURSIVE_MUTEXES 1
#define configUSE_TRACE_FACILITY 1
#define configUSE_STATS_FORMATTING_FUNCTIONS 1

#define ESP_CONNECT_LOGGING_LEVEL ESP_LOG_DEBUG

#define RPC_PROTOCOL 'A'
#define RPC_RESPONSE 'B'
#define RPC_VOID_RESPONSE 'b'
#define RPC_EXCEPTION 'C'
#define RPC_ASYNC_RESPONSE 'D'
#define RPC_ASYNC_VOID_RESPONSE 'd'
#define RPC_ASYNC_EXCEPTION 'E'
#define RPC_LOG_MESSAGE 'F'
#define RPC_BOOT 'G'

#define UART_NO UART_NUM_1
#define UART_BAUDRATE 9600
#define UART_RX_BUFFER_SIZE (2*1024)
#define UART_TX_BUFFER_SIZE (4*1024)

#define UART_TIMEOUT_MS 50000
#define UART_TX  GPIO_NUM_17
#define UART_RX  GPIO_NUM_16
#define UART_RTS GPIO_NUM_18
#define UART_CTS GPIO_NUM_19

#define RPC_TASK_NO 4
#define RPC_TASK_STACK_SIZE (12*1024)

#endif
